/* generated by tools/gen_u32_asset_ranges.py - asset arrays emitted as u32[] (texel/TLUT
 * bytes at address ^ 3 on the little-endian build, not ^ 7 like u64[] assets) */
#include "port_u32_assets.h"

extern const unsigned int gHylianMan1BeardedEarTex[] __attribute__((weak));
extern const unsigned int gHylianMan1BeardedEyeClosedTex[] __attribute__((weak));
extern const unsigned int gHylianMan1BeardedEyeHalfTex[] __attribute__((weak));
extern const unsigned int gHylianMan1BeardedEyeOpenTex[] __attribute__((weak));
extern const unsigned int gHylianMan1BeardedHairTex[] __attribute__((weak));
extern const unsigned int gHylianMan1BeardedSkinHairTex[] __attribute__((weak));
extern const unsigned int gHylianMan1BeardedSkinTex[] __attribute__((weak));
extern const unsigned int gHylianMan1FingersTex[] __attribute__((weak));
extern const unsigned int gHylianMan1PantsBeltTex[] __attribute__((weak));
extern const unsigned int gHylianMan1PantsTex[] __attribute__((weak));
extern const unsigned int gHylianMan1ShirtTex[] __attribute__((weak));
extern const unsigned int gHylianMan1ShoesTex[] __attribute__((weak));
extern const unsigned int gHylianMan1TLUT[] __attribute__((weak));
extern const unsigned int gHylianMan2BeltShoeTex[] __attribute__((weak));
extern const unsigned int gHylianMan2FingersTex[] __attribute__((weak));
extern const unsigned int gHylianMan2MustachedEarTex[] __attribute__((weak));
extern const unsigned int gHylianMan2MustachedEyeClosedTex[] __attribute__((weak));
extern const unsigned int gHylianMan2MustachedEyeHalfTex[] __attribute__((weak));
extern const unsigned int gHylianMan2MustachedEyeOpenTex[] __attribute__((weak));
extern const unsigned int gHylianMan2MustachedHairTex[] __attribute__((weak));
extern const unsigned int gHylianMan2MustachedMouthTex[] __attribute__((weak));
extern const unsigned int gHylianMan2MustachedSkinTex[] __attribute__((weak));
extern const unsigned int gHylianMan2PantsTex[] __attribute__((weak));
extern const unsigned int gHylianMan2ShirtTex[] __attribute__((weak));
extern const unsigned int gHylianMan2TLUT[] __attribute__((weak));
extern const unsigned int gHylianOldManClothesCapTex[] __attribute__((weak));
extern const unsigned int gHylianOldManClothesSideTex[] __attribute__((weak));
extern const unsigned int gHylianOldManEyeClosedTex[] __attribute__((weak));
extern const unsigned int gHylianOldManEyeHalfTex[] __attribute__((weak));
extern const unsigned int gHylianOldManEyeOpenTex[] __attribute__((weak));
extern const unsigned int gHylianOldManForeheadTex[] __attribute__((weak));
extern const unsigned int gHylianOldManHairTex[] __attribute__((weak));
extern const unsigned int gHylianOldManMouthTex[] __attribute__((weak));
extern const unsigned int gHylianOldManNoseTex[] __attribute__((weak));
extern const unsigned int gHylianOldManSkinTex[] __attribute__((weak));
extern const unsigned int gHylianOldManTLUT[] __attribute__((weak));
extern const unsigned int gHylianYoungWomanBrownHairFaceTex[] __attribute__((weak));
extern const unsigned int gHylianYoungWomanBrownHairSkinTex[] __attribute__((weak));
extern const unsigned int gHylianYoungWomanBrownHairTex[] __attribute__((weak));
extern const unsigned int gHylianYoungWomanCollarTex[] __attribute__((weak));
extern const unsigned int gHylianYoungWomanDressTex[] __attribute__((weak));
extern const unsigned int gHylianYoungWomanHandTex[] __attribute__((weak));
extern const unsigned int gHylianYoungWomanSkinTex[] __attribute__((weak));
extern const unsigned int gHylianYoungWomanTLUT[] __attribute__((weak));
extern const unsigned int gKm1BootWrinkleTex[] __attribute__((weak));
extern const unsigned int gKm1Ear1Tex[] __attribute__((weak));
extern const unsigned int gKm1Ear2Tex[] __attribute__((weak));
extern const unsigned int gKm1HairTex[] __attribute__((weak));
extern const unsigned int gKm1HandTex[] __attribute__((weak));
extern const unsigned int gKm1Skin1Tex[] __attribute__((weak));
extern const unsigned int gKm1Skin2Tex[] __attribute__((weak));
extern const unsigned int gKm1TLUT_0000FC[] __attribute__((weak));
extern const unsigned int gKm1TLUT_00083C[] __attribute__((weak));
extern const unsigned int gKm1TunicFringeTex[] __attribute__((weak));
extern const unsigned int gKm1TunicTex[] __attribute__((weak));
extern const unsigned int gKm1UnusedHairTex[] __attribute__((weak));
extern const unsigned int gKw1BeltBuckleTex[] __attribute__((weak));
extern const unsigned int gKw1BootsTex[] __attribute__((weak));
extern const unsigned int gKw1EarTex[] __attribute__((weak));
extern const unsigned int gKw1EyeClosedTex[] __attribute__((weak));
extern const unsigned int gKw1EyeHalfTex[] __attribute__((weak));
extern const unsigned int gKw1EyeOpenTex[] __attribute__((weak));
extern const unsigned int gKw1HairTex[] __attribute__((weak));
extern const unsigned int gKw1HairlineTex[] __attribute__((weak));
extern const unsigned int gKw1HandTex[] __attribute__((weak));
extern const unsigned int gKw1MouthTex[] __attribute__((weak));
extern const unsigned int gKw1Skin1Tex[] __attribute__((weak));
extern const unsigned int gKw1Skin2Tex[] __attribute__((weak));
extern const unsigned int gKw1TunicTex[] __attribute__((weak));
extern const unsigned int gKw1UnusedEyeOpenTex[] __attribute__((weak));
extern const unsigned int object_kw1_TLUT_0000FC[] __attribute__((weak));
extern const unsigned int object_kw1_TLUT_000D3C[] __attribute__((weak));
extern const unsigned int object_kw1_Tex_00047C[] __attribute__((weak));
extern const unsigned int object_oF1s_TLUT_00011C[] __attribute__((weak));
extern const unsigned int object_oF1s_TLUT_0002CC[] __attribute__((weak));
extern const unsigned int object_oF1s_Tex_0004BC[] __attribute__((weak));
extern const unsigned int object_oF1s_Tex_0008BC[] __attribute__((weak));
extern const unsigned int object_oF1s_Tex_0018BC[] __attribute__((weak));
extern const unsigned int object_oF1s_Tex_0018FC[] __attribute__((weak));
extern const unsigned int object_oF1s_Tex_0019FC[] __attribute__((weak));
extern const unsigned int object_oF1s_Tex_001AFC[] __attribute__((weak));
extern const unsigned int object_oF1s_Tex_001B7C[] __attribute__((weak));
extern const unsigned int object_oF1s_Tex_001F7C[] __attribute__((weak));
extern const unsigned int object_oF1s_Tex_00257C[] __attribute__((weak));
extern const unsigned int object_oF1s_Tex_0025BC[] __attribute__((weak));
extern const unsigned int object_oF1s_Tex_002DBC[] __attribute__((weak));

const PortU32Asset gPortU32Assets[] = {
    { gHylianMan1BeardedEarTex, 64 },
    { gHylianMan1BeardedEyeClosedTex, 256 },
    { gHylianMan1BeardedEyeHalfTex, 256 },
    { gHylianMan1BeardedEyeOpenTex, 256 },
    { gHylianMan1BeardedHairTex, 256 },
    { gHylianMan1BeardedSkinHairTex, 256 },
    { gHylianMan1BeardedSkinTex, 64 },
    { gHylianMan1FingersTex, 256 },
    { gHylianMan1PantsBeltTex, 256 },
    { gHylianMan1PantsTex, 512 },
    { gHylianMan1ShirtTex, 64 },
    { gHylianMan1ShoesTex, 64 },
    { gHylianMan1TLUT, 512 },
    { gHylianMan2BeltShoeTex, 64 },
    { gHylianMan2FingersTex, 64 },
    { gHylianMan2MustachedEarTex, 64 },
    { gHylianMan2MustachedEyeClosedTex, 256 },
    { gHylianMan2MustachedEyeHalfTex, 256 },
    { gHylianMan2MustachedEyeOpenTex, 256 },
    { gHylianMan2MustachedHairTex, 128 },
    { gHylianMan2MustachedMouthTex, 512 },
    { gHylianMan2MustachedSkinTex, 64 },
    { gHylianMan2PantsTex, 64 },
    { gHylianMan2ShirtTex, 256 },
    { gHylianMan2TLUT, 512 },
    { gHylianOldManClothesCapTex, 256 },
    { gHylianOldManClothesSideTex, 64 },
    { gHylianOldManEyeClosedTex, 1024 },
    { gHylianOldManEyeHalfTex, 1024 },
    { gHylianOldManEyeOpenTex, 1024 },
    { gHylianOldManForeheadTex, 256 },
    { gHylianOldManHairTex, 64 },
    { gHylianOldManMouthTex, 64 },
    { gHylianOldManNoseTex, 64 },
    { gHylianOldManSkinTex, 64 },
    { gHylianOldManTLUT, 512 },
    { gHylianYoungWomanBrownHairFaceTex, 128 },
    { gHylianYoungWomanBrownHairSkinTex, 64 },
    { gHylianYoungWomanBrownHairTex, 64 },
    { gHylianYoungWomanCollarTex, 64 },
    { gHylianYoungWomanDressTex, 64 },
    { gHylianYoungWomanHandTex, 64 },
    { gHylianYoungWomanSkinTex, 64 },
    { gHylianYoungWomanTLUT, 512 },
    { gKm1BootWrinkleTex, 64 },
    { gKm1Ear1Tex, 64 },
    { gKm1Ear2Tex, 64 },
    { gKm1HairTex, 512 },
    { gKm1HandTex, 64 },
    { gKm1Skin1Tex, 64 },
    { gKm1Skin2Tex, 64 },
    { gKm1TLUT_0000FC, 512 },
    { gKm1TLUT_00083C, 192 },
    { gKm1TunicFringeTex, 512 },
    { gKm1TunicTex, 64 },
    { gKm1UnusedHairTex, 512 },
    { gKw1BeltBuckleTex, 64 },
    { gKw1BootsTex, 256 },
    { gKw1EarTex, 64 },
    { gKw1EyeClosedTex, 1024 },
    { gKw1EyeHalfTex, 1024 },
    { gKw1EyeOpenTex, 1024 },
    { gKw1HairTex, 512 },
    { gKw1HairlineTex, 128 },
    { gKw1HandTex, 64 },
    { gKw1MouthTex, 1024 },
    { gKw1Skin1Tex, 64 },
    { gKw1Skin2Tex, 64 },
    { gKw1TunicTex, 64 },
    { gKw1UnusedEyeOpenTex, 2048 },
    { object_kw1_TLUT_0000FC, 512 },
    { object_kw1_TLUT_000D3C, 464 },
    { object_kw1_Tex_00047C, 64 },
    { object_oF1s_TLUT_00011C, 432 },
    { object_oF1s_TLUT_0002CC, 496 },
    { object_oF1s_Tex_0004BC, 1024 },
    { object_oF1s_Tex_0008BC, 4096 },
    { object_oF1s_Tex_0018BC, 64 },
    { object_oF1s_Tex_0018FC, 256 },
    { object_oF1s_Tex_0019FC, 256 },
    { object_oF1s_Tex_001AFC, 128 },
    { object_oF1s_Tex_001B7C, 1024 },
    { object_oF1s_Tex_001F7C, 512 },
    { object_oF1s_Tex_00257C, 64 },
    { object_oF1s_Tex_0025BC, 1024 },
    { object_oF1s_Tex_002DBC, 2048 },
};
const int gPortU32AssetCount = 86;
