#!/usr/bin/env python3
"""bootflow.py - compare the boot flow (console logo, title screen, file select, ...) on N64 and 3DS.

Both sides boot NORMALLY (3DS: PORT_NORMAL_BOOT; N64: pristine reference, make_ref.sh bootflow mode)
with the same scripted controller input injected at the start of every GameState_Update
(bootflow_input.h), and are captured at the same update counts: which game state is running, the
SaveContext field by field, and the frames (saved as build/statediff/{n64,3ds}_boot_<name>.json for
fbdiff.py --tour boot_<name>).

Script: tools/statediff/bootflows/<name>.txt, lines "frame buttons stick_x stick_y" (as scripts/*.txt)
and "capture frame".
usage: bootflow.py NAME [--skip-n64] [--skip-3ds]
"""
import argparse, os, re, struct, subprocess, sys, time

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import statediff as SD  # noqa: E402
import tour as T  # noqa: E402
import rngtrace as RT  # noqa: E402
from gdbrsp import GdbRsp  # noqa: E402

ARM_NM = "/opt/devkitpro/devkitARM/bin/arm-none-eabi-nm"


def parse(name):
    steps, caps = [], []
    for line in open(os.path.join(HERE, "bootflows", name + ".txt")):
        line = line.split("#")[0].strip()
        if not line:
            continue
        f = line.split()
        if f[0] == "capture":
            caps.append(int(f[1]))
            continue
        mask = 0
        for b in f[1].split("|"):
            mask |= 0 if b == "0" else SD.BUTTONS[b.upper()]
        steps.append((int(f[0]), mask, int(f[2]), int(f[3])))
    return steps, sorted(caps)


def write_header(steps, caps):
    text = ("/* generated by tools/statediff/bootflow.py */\n#define BOOTFLOW_NCAP %d\n"
            "static s32 sBootFlowCaptures[] = { %s };\nstatic s32 sBootFlowScript[][4] = {\n%s\n};\n" %
            (len(caps), ", ".join(str(c) for c in caps) or "-1",
             "\n".join("    { %d, 0x%04X, %d, %d }," % s for s in steps) or "    { 0, 0, 0, 0 },"))
    path = os.path.join(SD.OUT, "bootflow_script.h")
    if not os.path.exists(path) or open(path).read() != text:
        open(path, "w").write(text)
    return path


def capture_n64(tag, hdr, ncap, layout):
    rom, elf = os.path.join(SD.OUT, "ref_%s.z64" % tag), os.path.join(SD.OUT, "ref_%s.elf" % tag)
    if not os.path.exists(rom) or os.path.getmtime(rom) < os.path.getmtime(hdr):
        SD.sh("tools/statediff/make_ref.sh '' '' '%s' '' bootflow" % tag, check=True)
    syms = SD.n64_symbols(elf)
    sym = RT.Symbolizer(SD.MIPS_NM, elf)
    anchor = syms["BootFlow_Captured"]
    SD.sh("pkill -9 -f MacOS/ares")
    time.sleep(1)
    ram = os.path.join(SD.OUT, "ref_%s.ram" % tag)  # fresh cartridge: no SRAM file (ares starts it at 0xFF)
    if os.path.exists(ram):
        os.remove(ram)
    subprocess.Popen([SD.ARES, "--system", "Nintendo 64", "--no-file-prompt", rom],
                     stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL, start_new_session=True)
    g = GdbRsp(port=9123, connect_wait=30)
    caps = {}
    try:
        g.set_break(anchor)
        g.cont_until(anchor, timeout=180)
        while True:
            gs = g.read_regs()[4] & 0xFFFFFFFF
            i = struct.unpack(">i", g.read_mem(syms["gBootFlowCaptureIdx"], 4))[0]
            main = struct.unpack(">I", g.read_mem(gs + 4, 4))[0]  # GameState.main (after gfxCtx)
            vi = struct.unpack(">I", g.read_mem(syms["__osViCurr"], 4))[0]
            disp = struct.unpack(">I", g.read_mem(vi + 4, 4))[0] | 0x80000000
            cfb = struct.unpack(">II", g.read_mem(syms["sSysCfbFbPtr"], 8))
            caps[i] = {"state": sym(main), "save": g.read_mem(syms["gSaveContext"], layout["SaveContext"]["size"]),
                       "play": b"", "actors": [], "glob": b"",
                       "fbdisp": g.read_mem(disp, 320 * 240 * 2),
                       "fb0": g.read_mem(cfb[0] | 0x80000000, 320 * 240 * 2),
                       "fb1": g.read_mem(cfb[1] | 0x80000000, 320 * 240 * 2),
                       "skin": g.read_mem(syms["gSkinLimbMatrices"], 60 * 64)}
            print("  N64 capture %d/%d  %s" % (i + 1, ncap, caps[i]["state"]), flush=True)
            if i + 1 >= ncap:
                break
            g.cont_until(anchor, timeout=180, from_addr=anchor)
    finally:
        try:
            g.detach()
        except Exception:
            pass
        SD.sh("pkill -9 -f MacOS/ares")
    return caps


def capture_3ds(ncap):
    SD.build_3ds("-DSTATEDIFF_BOOTFLOW -DPORT_NORMAL_BOOT -Itools/statediff -Ibuild/statediff")
    tour = [("boot", 0, "")] * ncap
    sav = os.path.join(SD.SD, "save.bin")  # fresh cartridge on the 3DS too
    if os.path.exists(sav):
        os.remove(sav)
    caps = T.capture_3ds_built(tour)
    sym = RT.Symbolizer(ARM_NM, os.path.join(SD.OUT, "3ds_tour.elf"))
    for i, c in caps.items():
        c["state"] = sym(struct.unpack("<I", c["play"][4:8])[0]) if len(c["play"]) >= 8 else "?"
    return caps


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("name")
    ap.add_argument("--skip-n64", action="store_true")
    ap.add_argument("--skip-3ds", action="store_true")
    a = ap.parse_args()
    steps, caps = parse(a.name)
    hdr = write_header(steps, caps)
    layout = SD.load_layout()
    tag = "boot_%s" % a.name
    pn, p3 = os.path.join(SD.OUT, "n64_%s.json" % tag), os.path.join(SD.OUT, "3ds_%s.json" % tag)
    n64 = T.load_caps(pn) if a.skip_n64 else capture_n64(tag, hdr, len(caps), layout)
    if not a.skip_n64:
        T.save_caps(pn, n64)
    ds = T.load_caps(p3) if a.skip_3ds else capture_3ds(len(caps))
    if not a.skip_3ds:
        T.save_caps(p3, ds)
    allow = [re.compile(l.split("#")[0].strip()) for l in open(os.path.join(HERE, "allow.txt"))
             if l.split("#")[0].strip()]
    print("\nboot flow '%s': %d captures, N64 reached %d, 3DS reached %d" % (a.name, len(caps), len(n64), len(ds)))
    for i, frame in enumerate(caps):
        if i not in n64 or i not in ds:
            print("  %-3d frame %-5d NOT REACHED on %s" % (i, frame, " and ".join(
                s for s, c in (("N64", n64), ("3DS", ds)) if i not in c)))
            continue
        out = []
        SD.diff_struct(layout, "SaveContext", n64[i]["save"], ds[i]["save"], "", False, out)
        out = [o for o in out if not any(r.search(o[0]) for r in allow)]
        sn, s3 = n64[i].get("state", "?"), ds[i].get("state", "?")
        print("  %-3d frame %-5d N64 %-22s 3DS %-22s save %s" % (i, frame, sn, s3,
                                                                  "OK" if not out else "%d DIFFERENCES" % len(out)))
        for path, x, y in out[:6]:
            print("        %-58s N64=%-12s 3DS=%s" % (path[:58], SD.fmt(x), SD.fmt(y)))
        sa, sb = n64[i].get("skin", b""), ds[i].get("skin", b"")
        if len(sa) == len(sb) == 60 * 64:
            fa, fb = struct.unpack(">960f", sa), struct.unpack("<960f", sb)
            bad = [k for k in range(960) if abs(fa[k] - fb[k]) > 1e-2 * max(1.0, abs(fa[k]))]
            print("        gSkinLimbMatrices: %s" % ("identical" if not bad else "%d of 960 floats differ, first limb %d: N64 %s / 3DS %s" % (
                len(bad), bad[0] // 16, [round(v, 3) for v in fa[bad[0] // 16 * 16:bad[0] // 16 * 16 + 16]],
                [round(v, 3) for v in fb[bad[0] // 16 * 16:bad[0] // 16 * 16 + 16]])))


if __name__ == "__main__":
    main()
