#!/usr/bin/env python3
"""gen_u32_asset_ranges.py - list the asset arrays the decomp emits as u32[] (instead of u64[]).

Texture/palette data is read by the port's renderer in N64 byte order. For the usual u64[] asset
arrays the little-endian build keeps logical byte k at address ^ 7; for u32[] arrays (object_km1,
object_kw1, ... - textures that are only 4-byte aligned in the ROM) it is at address ^ 3. The renderer
looks each texture/TLUT source up in this table (port/src/gfx/gfx_pc.c).

usage: tools/gen_u32_asset_ranges.py   (after the decomp's asset build; writes port/src_gen/u32_asset_ranges.c)
"""
import os, re

REPO = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
EXTRACTED = os.path.join(REPO, "extracted/ntsc-1.0")
BUILD = os.path.join(REPO, "build/ntsc-1.0")
OUT = os.path.join(REPO, "port/src_gen/u32_asset_ranges.c")

DECL = re.compile(r'^u32 (\w+)\[[^\]]*\] = \{\n#include "([^"]+\.u32\.inc\.c)"', re.M)


def main():
    entries = []
    for root, _, files in os.walk(os.path.join(EXTRACTED, "assets")):
        for f in sorted(files):
            if f.endswith(".c"):
                for m in DECL.finditer(open(os.path.join(root, f), errors="ignore").read()):
                    inc = os.path.join(BUILD, m.group(2))
                    words = len(re.findall(r"0x[0-9A-Fa-f]+", open(inc).read()))
                    entries.append((m.group(1), words * 4))
    entries.sort()
    with open(OUT, "w") as out:
        out.write("/* generated by tools/gen_u32_asset_ranges.py - asset arrays emitted as u32[] (texel/TLUT\n"
                  " * bytes at address ^ 3 on the little-endian build, not ^ 7 like u64[] assets) */\n")
        out.write('#include "port_u32_assets.h"\n\n')
        for name, _ in entries:
            out.write("extern const unsigned int %s[] __attribute__((weak));\n" % name)
        out.write("\nconst PortU32Asset gPortU32Assets[] = {\n")
        for name, size in entries:
            out.write("    { %s, %d },\n" % (name, size))
        out.write("};\nconst int gPortU32AssetCount = %d;\n" % len(entries))
    print("%d u32 asset arrays -> %s" % (len(entries), os.path.relpath(OUT, REPO)))


if __name__ == "__main__":
    main()
