#!/usr/bin/env python3
"""gen_overlay_statics.py - table of every overlay's static-data sections for port/src/overlay_statics.c.

On the N64, loading an overlay (Overlay_Load) copies its .data fresh from ROM and zeroes its .bss, so
an actor/effect/gamestate overlay's static variables start over whenever the game reloads it (e.g.
ObjectKankyo's sIsSpawned). The port links overlay code natively; Makefile.3ds renames each overlay
object's .data/.bss to ovld_<ovl>/ovlb_<ovl> so the linker provides __start_/__stop_ bounds, and
overlay_statics.c restores them at Overlay_Load, keyed by the overlay's ROM start (vromStart).
Writes port/src_gen/overlay_statics_table.inc.
"""
import os, re

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
rom = dict(re.findall(r"^_(ovl_\w+)SegmentRomStart = (0x[0-9a-fA-F]+);", open(os.path.join(REPO, "port/rom_symbols.ld")).read(), re.M))
ovls, missing = [], []
for kind in sorted(os.listdir(os.path.join(REPO, "src/overlays"))):
    d = os.path.join(REPO, "src/overlays", kind)
    for name in sorted(os.listdir(d)):
        if name.startswith("ovl_") and os.path.isdir(os.path.join(d, name)):
            (ovls if name in rom else missing).append(name)
lines = ["/* generated by tools/gen_overlay_statics.py - do not edit */"]
for o in ovls:
    lines.append("extern char __start_ovld_%s[] __attribute__((weak)), __stop_ovld_%s[] __attribute__((weak));" % (o, o))
    lines.append("extern char __start_ovlb_%s[] __attribute__((weak)), __stop_ovlb_%s[] __attribute__((weak));" % (o, o))
lines.append("static const OverlayStatics sOverlayStatics[] = {")
for o in ovls:
    lines.append("    { %s, __start_ovld_%s, __stop_ovld_%s, __start_ovlb_%s, __stop_ovlb_%s }," % (rom[o], o, o, o, o))
lines.append("};")
open(os.path.join(REPO, "port/src_gen/overlay_statics_table.inc"), "w").write("\n".join(lines) + "\n")
print("%d overlays in table; no ROM symbol for: %s" % (len(ovls), missing))
